Repository Git-For-Geeks/Data-Science-Tools, pull requests merged in 2022-10, with the labels that each got.

#16 added matplotlib
  Dataset/company_sales_data.csv
  Prashant/Matplotlib.ipynb
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, easy

#17 added numpy
  Prashant/Numpy.ipynb
Labels: git-for-geeks, easy

#18 added data cleaning ipynb
  Dataset/Toyota.csv
  Prashant/Data Cleaning.ipynb
Labels: git-for-geeks, easy

#19 added seaborn
  Prashant/Seaborn.ipynb
Labels: git-for-geeks, easy

#20 added regular expression
  Prashant/Regular expressions.ipynb
Labels: git-for-geeks, easy

#21 added web scraping
  Prashant/Web Scraping.ipynb
Labels: git-for-geeks, medium

#22 Unemployment dataset visualization
  JanWeeee/E_commerce_dataset.ipynb
  JanWeeee/FIFA_23.ipynb
  JanWeeee/Unemployment_dataset_visualization.ipynb
Labels: git-for-geeks, medium, hacktoberfest

#28 Geopy Folium
  JanWeeee/Geopy_folium.ipynb
Labels: good first issue, git-for-geeks, medium, hacktoberfest

#30 Regular Expression
  JanWeeee/Regular expression.ipynb
Labels: git-for-geeks, medium

#31 Visualization of flipkart website
  JanWeeee/Web Scrapping on Flipkart website.ipynb
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#32 Sansgupta25-California housing dataset
  Dataset/housing.csv
  Sansgupta25/Visualization on California Housing Prices.ipynb
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#34 Visualization using seaborn on supermarket sales dataset
  JanWeeee/Visualization using seaborn on supermarket sales dataset.ipynb
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#35 Visualization on Company sales data dataset
  JanWeeee/Visualization on Company sales data dataset.ipynb
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#39 added Instagram reach analysis
  Prashant/Instagram Reach Analysis.ipynb
  Prashant/Instagram.csv
Labels: git-for-geeks, medium, hacktoberfest

#41 added IPL 2022 analysis
  Prashant/IPL 2022 Analysis.ipynb
  Prashant/IPL 2022.csv
  Prashant/Instagram Reach Analysis.ipynb
Labels: git-for-geeks, medium, hacktoberfest

#42 Data cleaning on toyota dataset
  JanWeeee/Data cleaning on Toyota dataset.ipynb
Labels: git-for-geeks, medium, hacktoberfest

#44 added Unemployment Analysis
  Prashant/Unemployment Analysis.ipynb
Labels: git-for-geeks, medium

#46 Visualization on student performance dataset
  Divyanshu/Datavisualds.ipynb
Labels: git-for-geeks, hacktoberfest-accepted, easy
